version: 0.2

phases:
  pre_build:
    commands:
      - cp .env.production .env

  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --legacy-peer-deps

  build:
    commands:
      - echo Building the React app...
      - export NODE_OPTIONS="--max-old-space-size=4096"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: no